rate = input("What's the exchange rate for Euro to Dollars?")
print(input)
amount = input("How many Euros would you like to exchange?")
print(input)
strnum =  int(rate)
strnum2 = int(amount)
strnum3 = (strnum/strnum2)
total = (strnum3)
result = (total - 3)
print(result)